DO $$ DECLARE pagbank_id UUID; c6_id UUID; din_id UUID;
BEGIN
  SELECT id INTO pagbank_id FROM contas_financeiras WHERE tipo='pagbank_pj' LIMIT 1;
  SELECT id INTO c6_id FROM contas_financeiras WHERE tipo='c6_pf' LIMIT 1;
  SELECT id INTO din_id FROM contas_financeiras WHERE tipo='dinheiro' LIMIT 1;

  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-05-31', 5.28239, 'geral', 'outros', 'pix', c6_id, 'pago', 'Acerto de caixa para inicio do sistema');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-05-31', 13.28921, 'geral', 'outros', 'pix', pagbank_id, 'pago', 'Acerto de caixa para inicio do sistema');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-01', 50000, 'geral', 'outros', pagbank_id, 'pago', 'Compra de celular', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-01', 92223, 'geral', 'outros', pagbank_id, 'pago', 'Empréstimo da obra', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 1.2825, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 15000, 'outros', 'festa', 'pix', pagbank_id, 'pago', 'festa do Milo | Pet: Milo');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 37800, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 13000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 40000, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'Conta wallace | Pet: Lua');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 8500, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Conta Wallace | Pet: Lua');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 77000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Paçoca | Pet: Paçoca (fiapo)');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Dominique');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 29500, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Nutella');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 7650, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Paçoca | Pet: Paçoca (fiapo)');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 8300, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Tobby');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 44000, 'creche', 'diaria_avulsa', 'pix', c6_id, 'pago', 'Akira');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-02', 18595, 'loja', 'produtos_banho_tosa', pagbank_id, 'pago', 'Budopet', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Frida');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 15000, 'outros', 'festa', 'pix', c6_id, 'pago', 'Timão');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 11000, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Minnie');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 41225, 'geral', 'outros', pagbank_id, 'pago', 'Guia do fgts', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 92612, 'geral', 'outros', pagbank_id, 'pago', 'Darf', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 10000, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Gary');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 29700, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Jorginho');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 53500, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Luna e Nalu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 7650, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 24000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 38750, 'loja', 'racao_petiscos', pagbank_id, 'pago', 'Natuka', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 29700, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Ziggy');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 12000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Ziggy');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 17550, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Lilica e lukinha | Pet: Lilica e Lukinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 66000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 21000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 7650, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 15000, 'banho_tosa', 'banho_tosa', 'dinheiro', din_id, 'pago', 'banho | Pet: Lolla e Kobe');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 10800, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'Logan');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1.48808, 'banho_tosa', 'produtos_banho_tosa', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1.42261, 'creche', 'salarios', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1.2857, 'creche', 'salarios', pagbank_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-04', 29700, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Cookie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-04', 12900, 'banho_tosa', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Cookie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 12000, 'banho_tosa', 'banho_tosa', 'dinheiro', din_id, 'pago', 'Safira');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 5000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Dom');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 7000, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Otto');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 5000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Spike');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 90000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 6000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 1.41, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-05', 4.84819, 'geral', 'taxas_bancarias', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-05', 37500, 'transporte', 'combustivel', din_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 2890, 'loja', 'venda_produto', 'pix', pagbank_id, 'pago', 'Pandorinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 27350, 'geral', 'venda_produto', 'dinheiro', din_id, 'pago', NULL);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-06', 24350, 'geral', 'manutencao', din_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 790, 'geral', 'outros', 'pix', pagbank_id, 'pago', NULL);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-06', 58800, 'geral', 'manutencao', c6_id, 'pago', 'Material de construção', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 45000, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'charlie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-07', 15000, 'geral', 'outros', 'pix', pagbank_id, 'pago', 'Freelancer lorrany');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 7300, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 2460, 'loja', 'venda_produto', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 18000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 25000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Milo');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 40000, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Zico');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 39500, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Matilda');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 39500, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Brida');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 48000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Felicia');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 24000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Felicia');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 29700, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Lurdinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 27000, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 24000, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 7200, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 5000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Zico');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 10000, 'outros', 'outros', 'pix', pagbank_id, 'pago', 'v8 | Pet: Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 10000, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 2500, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 44000, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Jake');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 15600, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Jake');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 23000, 'outros', 'outros', 'pix', pagbank_id, 'pago', 'v8, ar e kc | Pet: Jake');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 37600, 'geral', 'contador', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 12286, 'geral', 'agua_luz_internet', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 4, 'geral', 'outros', pagbank_id, 'pago', 'Salário Carol', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 4, 'geral', 'outros', pagbank_id, 'pago', 'Salário Mariana', false);
END $$;