DO $$ DECLARE pagbank_id UUID; c6_id UUID; din_id UUID;
BEGIN
  SELECT id INTO pagbank_id FROM contas_financeiras WHERE tipo='pagbank_pj' LIMIT 1;
  SELECT id INTO c6_id FROM contas_financeiras WHERE tipo='c6_pf' LIMIT 1;
  SELECT id INTO din_id FROM contas_financeiras WHERE tipo='dinheiro' LIMIT 1;

  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-05-31', 5282.39, 'geral', 'outros', 'pix', c6_id, 'pago', 'Acerto de caixa para inicio do sistema');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-05-31', 13289.21, 'geral', 'outros', 'pix', pagbank_id, 'pago', 'Acerto de caixa para inicio do sistema');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-01', 500, 'geral', 'outros', pagbank_id, 'pago', 'Compra de celular', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-01', 922.23, 'geral', 'outros', pagbank_id, 'pago', 'Empréstimo da obra', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 1282.5, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 150, 'outros', 'festa', 'pix', pagbank_id, 'pago', 'festa do Milo | Pet: Milo');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 378, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 130, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Shibas');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 400, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'Conta wallace | Pet: Lua');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-01', 85, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Conta Wallace | Pet: Lua');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 770, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Paçoca | Pet: Paçoca (fiapo)');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Dominique');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 295, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Nutella');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 76.5, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Paçoca | Pet: Paçoca (fiapo)');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 83, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Tobby');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-02', 440, 'creche', 'diaria_avulsa', 'pix', c6_id, 'pago', 'Akira');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-02', 185.95, 'loja', 'produtos_banho_tosa', pagbank_id, 'pago', 'Budopet', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Frida');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 150, 'outros', 'festa', 'pix', c6_id, 'pago', 'Timão');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 110, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Minnie');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 412.25, 'geral', 'outros', pagbank_id, 'pago', 'Guia do fgts', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 926.12, 'geral', 'outros', pagbank_id, 'pago', 'Darf', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 100, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Gary');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 297, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Jorginho');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 535, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Luna e Nalu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 76.5, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 240, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Lis');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-03', 387.5, 'loja', 'racao_petiscos', pagbank_id, 'pago', 'Natuka', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 297, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Ziggy');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 120, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Ziggy');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 175.5, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Lilica e lukinha | Pet: Lilica e Lukinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 660, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 210, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 76.5, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 150, 'banho_tosa', 'banho_tosa', 'dinheiro', din_id, 'pago', 'banho | Pet: Lolla e Kobe');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-03', 108, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'Logan');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1488.08, 'banho_tosa', 'produtos_banho_tosa', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1422.61, 'creche', 'salarios', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-04', 1285.7, 'creche', 'salarios', pagbank_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-04', 297, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Cookie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-04', 129, 'banho_tosa', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Cookie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 120, 'banho_tosa', 'banho_tosa', 'dinheiro', din_id, 'pago', 'Safira');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 50, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Dom');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 70, 'banho_tosa', 'banho_tosa', 'pix', c6_id, 'pago', 'Otto');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 50, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Spike');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 900, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 60, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 1410, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Ferrugem e chiara');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-05', 4848.19, 'geral', 'taxas_bancarias', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-05', 375, 'transporte', 'combustivel', din_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-05', 28.9, 'loja', 'venda_produto', 'pix', pagbank_id, 'pago', 'Pandorinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 273.5, 'geral', 'venda_produto', 'dinheiro', din_id, 'pago', NULL);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-06', 243.5, 'geral', 'manutencao', din_id, 'pago', NULL, false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 7.9, 'geral', 'outros', 'pix', pagbank_id, 'pago', NULL);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-06', 588, 'geral', 'manutencao', c6_id, 'pago', 'Material de construção', false);
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-06', 450, 'hotel', 'hotel', 'pix', c6_id, 'pago', 'charlie');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-07', 150, 'geral', 'outros', 'pix', pagbank_id, 'pago', 'Freelancer lorrany');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 73, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 24.6, 'loja', 'venda_produto', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 180, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Mel');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 250, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Milo');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 400, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Zico');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 395, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Matilda');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 395, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Brida');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 480, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Felicia');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 240, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Felicia');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 297, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Lurdinha');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 270, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 240, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Zuzu');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 72, 'hotel', 'hotel', 'pix', pagbank_id, 'pago', 'Maya');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-08', 50, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Zico');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 100, 'outros', 'outros', 'pix', pagbank_id, 'pago', 'v8 | Pet: Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 100, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 25, 'transporte', 'transporte', 'pix', pagbank_id, 'pago', 'Luck spitz');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 440, 'creche', 'diaria_avulsa', 'pix', pagbank_id, 'pago', 'Jake');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 156, 'banho_tosa', 'banho_tosa', 'pix', pagbank_id, 'pago', 'Jake');
  INSERT INTO receitas (data, valor, area, categoria, forma_pagamento, conta_id, status, descricao) VALUES ('2026-06-09', 230, 'outros', 'outros', 'pix', pagbank_id, 'pago', 'v8, ar e kc | Pet: Jake');
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 376, 'geral', 'contador', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 122.86, 'geral', 'agua_luz_internet', pagbank_id, 'pago', NULL, false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 4000, 'geral', 'outros', pagbank_id, 'pago', 'Salário Carol', false);
  INSERT INTO despesas (data, valor, area, categoria, conta_id, status, descricao, investimento) VALUES ('2026-06-09', 4000, 'geral', 'outros', pagbank_id, 'pago', 'Salário Mariana', false);
END $$;